### PR TITLE
[WIP] Tensorforce 5.0 upgrades

### PR DESCRIPTION
**Pull request by K-Kit**
Started upgrading to tensorforce 5.0
- changed from gym.env to tensorforce Environment (typing was breaking the runner)
- Issue with _next_observation

```
Traceback (most recent call last):
  File ".\main.py", line 43, in <module>
    performance = strategy.run(steps=100000, should_train=True)
  File "D:\dev\tensortrade\tensortrade\strategies\tensorforce_trading_strategy.py", line 148, in run
    max_episode_timesteps=self._max_episode_timesteps,
  File "C:\Python37\lib\site-packages\tensorforce-0.5.0-py3.7.egg\tensorforce\execution\runner.py", line 225, in run
    evaluation=self.evaluation
  File "C:\Python37\lib\site-packages\tensorforce-0.5.0-py3.7.egg\tensorforce\execution\runner.py", line 305, in run_episode
    states = environment.reset()
  File "D:\dev\tensortrade\tensortrade\environments\trading_environment.py", line 247, in reset
    return self._next_observation(Trade('N/A', 'hold', 0, 0))
  File "D:\dev\tensortrade\tensortrade\environments\trading_environment.py", line 159, in _next_observation
    observation = self._feature_pipeline.fit_transform(observation)
  File "D:\dev\tensortrade\tensortrade\features\feature_pipeline.py", line 84, in fit_transform
    raise ValueError(f'Invalid observation frame passed to feature pipeline: {e}')
ValueError: Invalid observation frame passed to feature pipeline: Expected 2D array, got 1D array instead:
array=[10000.  10010.  10000.  10010.    130.9].
```

### CODE REVIEW

**Comment by K-Kit** [comment]
@notadamking I believe its very close to working but I'm still trying to figure out what the intended logic is here

**Comment by notadamking** [comment]
@K-Kit thanks for this, I will be integrating it today.

**Comment by codeninja** [comment]
@notadamking where are you with the merge of this PR? Anything we can do to assist?

**Comment by notadamking** [comment]
@codeninja, I was in the process of integrating Tensorforce 0.5.0, but realized the library was not yet ready to integrate. I have submitted multiple feature requests on their repo, which have since been resolved. I will need to check if the latest version supports the functionality we need.

**Comment by codeninja** [comment]
After going down this path all day today I believe the openai package is
going to pose another challenge. Specifically the state_from_space method
seems to have been refactored out.

**Comment by notadamking** [comment]
Check out https://github.com/notadamking/tensortrade/tree/tensorforce0.5.1-upgrade

**Pull request closed without merging**
