### PR TITLE
Built necessary Docker infrastructure to run python notebooks, build documentation, and run test suite

### PR DESCRIPTION
**Pull request by dru-zod**
I've finished my work on the Docker infrastructure. I had to make some changes to the versions of tensorforce to get things running.

### CODE REVIEW

**Comment by notadamking** [comment]
@dru-zod thanks for this, will look at it later today and see if I can get it merged.

**Comment by notadamking** [comment]
I get some errors while running the commands:

```bash
$ make run-notebook
docker run -t --rm -p=8888:8888 "tensortrade:latest" jupyter notebook --ip='*' --port=8888 --no-browser --allow-root /examples/
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.5/site-packages/jupyter_core/command.py", line 134, in _jupyter_abspath
    'Jupyter command `{}` not found.'.format(jupyter_subcommand)
Exception: Jupyter command `jupyter-notebook` not found.
```

and

```bash
$ make run-docs
docker run -t --name documentation "tensortrade:latest" make docs-build
docker: Error response from daemon: Conflict. The container name "/documentation" is already in use by container "bf3b7623ed05083a8eef109c159522c9619b7047b1103ba0511f4a5a0082bfc9". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
make: *** [run-docs] Error 125
```

**Comment by dru-zod** [comment]
Hmm that's odd. Did you build the image with "make build-cpu" first? My image is based on python3.6. I've double checked and things are working for me, but I could be missing something

**Comment by notadamking** [comment]
@dru-zod I had forgotten to run `make build-cpu` first. Perhaps a `build-cpu-if-not-built` command should be added to each of the `run-*` commands.

This fixed each of the commands except `run-docs`, which still gives the same error. I believe it has to do with the way you are creating a named container to copy the `/docs` directory from.

**Comment by dru-zod** [comment]
I've updated the makefile with your suggestions, let me know if this is what you had in mind, if not I can work some more on it over the weekend

**Comment by notadamking** [comment]
Thanks @dru-zod. Looks good, I've got it merged.

Any chance you know how to automatically open a browser w/ the Jupyter notebook being run in Docker?

**Comment by dru-zod** [comment]
@notadamking I'm not sure how to do that, I usually just copy the link

**Pull request merged**
