### PR TITLE
TargetStopActionStrategy - Gitcoin Request

### PR DESCRIPTION
**Pull request by LatiinB**
This is the requested feature from issue 46 (https://github.com/notadamking/tensortrade/issues/46)
It is a variation on DiscreteActionStrategy in which there is a profit target and stop-loss for each trade, which is recorded statefully as a part of the class init, in percentages.
Based on the selected profit target and stop-loss, which both default to 1%, if a trade goes above the profit target or below the stop loss (or equals either) the program must use that timestep to trade the oldest amount bought.

### CODE REVIEW

**Comment by LatiinB** [comment]
I have reviewed the files and cannot find the issue; the tests on my computer pass the ta-lib check as i have installed the ta-lib files via homebrew, which the building client does not seem to have done. Additionally, my build fails the fractional difference test even without the committed file, and so I do not know what the issue is.

**Comment by notadamking** [comment]
@LatiinB looks great! Don't worry about the failing FractionalDifference unit tests, those are being worked on. Ta-lib is also being replaced w/ an open source, non-binary-requiring library.

If you could create unit tests for this component, I can get it merged and grant you the bounty!

**Comment by LatiinB** [comment]
Hey @notadamking , I added the test for the new action strategy, and I also updated TargetStopActionStrategy to have some optional test functionality to make unit testing it easier, as well as adding the TargetStopActionStrategy to the actions/__init__.py

**Comment by LatiinB** [comment]
However, when testing the action strategy, it gets caught on an Attribute exception wherein self._exchange is not an attribute of the class; this is used in the other action strategies such as DiscreteActionStrategy so i'm not sure what the issue is.

**Comment by notadamking** [comment]
Hey, I pulled down your PR and worked on it, because it's close but not quite what I need.

Go check out the branch I created, and see if you can figure out how to make `profit_target_percent`, `stop_loss_percent`, and `trade_amount` work correctly, as defined, with a `gym.Space`. 

Then we'll need to update the tests to pass. The `exchange` can be passed in as a fixture, so no extra parameters will need to be passed in to the strategy. If you'd like, you can create a `TestExchange` that implements `InstrumentExchange` to make testing simpler.

**Comment by LatiinB** [comment]
Hey @notadamking 
I've committed the updated TargetStopActionStrategy [here](https://github.com/LatiinB/tensortrade/blob/master/tensortrade/actions/target_stop_action_strategy.py).
I corrected the trade amount calculations and added dynamic calculations for the profit and stop loss percentages, which are inverse to the amounts being traded so that small trades require more profit/loss to be worth selling, and vice versa, which is explained in the docu-string. I also made a couple basic unit tests for the strategy [here](https://github.com/LatiinB/tensortrade/blob/master/tests/tensortrade/actions/test_target_stop_action_strategy.py).

If you could look over the strategy and see if everything is what you need? Specifically, I wasn't sure how you wanted the timeout to work, how you wanted the profit/stop to be dynamically calculated, and which types of unit tests you need?

**Comment by notadamking** [comment]
@LatiinB thanks for your work on this, I apologize for not getting to it sooner. I will get it reviewed/merged if possible this week.

**Comment by notadamking** [comment]
@LatiinB after looking into the code more closely, it seems the `profit_target_percent` and `stop_loss_percent` are being calculated in a manner that does not give the agent much control. We will need to come up with a better action structure to allow the agent full control of the entire profit target %, stop loss %, and position size spectrum.

**Comment by LatiinB** [comment]
@notadamking,
I'm really sorry for not updating the PR recently, I have had a lot of schoolwork in the past weeks! :)
I added arguments to the get_trade function to allow the agent to pass in values for the profit and stop loss percents. These are then rounded to stay within the set range for the strategy.
You can find the new file [here](https://github.com/LatiinB/tensortrade/blob/master/tensortrade/actions/target_stop_action_strategy.py).

**Comment by LatiinB** [comment]
I also added a few tests to the unit test file and updated them.

**Comment by notadamking** [comment]
@LatiinB adding the parameters to the `get_trade` function does not work, as this function is used generically by the `TradingEnvironment` for any `ActionScheme`.

**Comment by LatiinB** [comment]
@notadamking, sorry but I haven't been able to find a way to dynamically calculate the profit target and stop loss percentages without an additional argument in the get_trade function. 
The only other way it could be controlled at all by the agent that i can find is by stepping through the range an equal amount of times to the action chosen, however this seems very arbitrary and does not let the agent actually control the percentages.

Feel free to use anything I've done if it helps, and again sorry for being unable to find a way to implement this feature.
:)

**Pull request closed without merging**
