### PR TITLE
Added support for calling tensortrade components by string.

### PR DESCRIPTION
**Pull request by mwbrulhardt**
I have added in code to be able to call different tensortrade components by name. The following is an example of how to use it:

```python
import tensortrade.actions as actions

action_strategy_class = actions.get('discrete')
```
In addition to `actions`, I have also given this same functionality to:
*  `exchanges`
*  `rewards`
*  `slippage`
*  `strategies`

This is useful in situations where one would want to create an instance of a trading environment quickly, without have to import all of the classes that they want. Once their settings become more complicated, they would then import the class and adjust the settings as needed. 

This is based on the way Keras works to instantiate models by either giving the strings or the actual classes as input. 

When certain environments and configurations later on become a standard or benchmark, this will also serve well to easily call them and give easy access for people who are new to the library and want to try it out in a quick start manner. It would be the same kind of standard that gym has for its environments, such as being able to start `cartpole-v1` quickly for beginners.

Hope this is helpful and can't wait to do more! Love the library!

### CODE REVIEW

**Comment by notadamking** [comment]
First off, thanks for the contribution.

I am curious what the advantage of the proposed syntax is over using the following code:

```python
import tensortrade.actions as actions

action_strategy_class = actions.DiscreteActionStrategy
```

Or, more simply, since we no longer need an intermediary `action_strategy_class` variable:

```python
import tensortrade.actions as actions

strategy = actions.DiscreteActionStrategy(...optionalArgs)
```

**Comment by mwbrulhardt** [comment]
> First off, thanks for the contribution.
> 
> I am curious what the advantage of the proposed syntax is over using the following code:
> 
> ```python
> import tensortrade.actions as actions
> 
> action_strategy_class = actions.DiscreteActionStrategy
> ```
> 
> Or, more simply, since we no longer need an intermediary `action_strategy_class` variable:
> 
> ```python
> import tensortrade.actions as actions
> 
> strategy = actions.DiscreteActionStrategy(...optionalArgs)
> ```

The advantage would not be in this particular instance, but when calling the environment. So for example instead of of calling all the classes you would use this instead:
```python
from tensortrade.environments import TradingEnvironment
environment = TradingEnvironment(exchange='gan',
                                 feature_pipeline=feature_pipeline,
                                 action_strategy='discrete',
                                 reward_strategy='simple')
```
This is similar to keras where instead of importing all of the classes and specifying their parameters you just do the following:
```python
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
```

So this implementation would become useful inside the __init__ method of the environment. Where you can just have:

```python
def __init___(self, exchange='gan', 
                    feature_pipeline=feature_pipeline, 
                    action_strategy='discrete',
                    reward_strategy='simple'):
      self.exchange = exchanges.get(exchange)() if isinstance(str, exchange) else exchange
      self.feature_pipeline = feature_pipeline
      self.action_strategy = actions.get(action_strategy)() if isinstance(str, action_strategy) else action_strategy
      self.reward_strategy = rewards.get(reward_strategy)() if isinstance(str, reward_strategy) else reward_strategy
```
In addition, later on when you have standard benchmarks you can call them using this same way. Like, ```environments.get('default)``` or something.

Also as for whether or not they return classes or objects that can be easily changed to just return the objects if that works better.

**Comment by notadamking** [comment]
> The advantage would not be in this particular instance, but when calling the environment. So for example instead of of calling all the classes you would use this instead:
> 
> ```python
> from tensortrade.environments import TradingEnvironment
> environment = TradingEnvironment(exchange='gan',
>                                  feature_pipeline=feature_pipeline,
>                                  action_strategy='discrete',
>                                  reward_strategy='simple')
> ```

Ahh, I get it now. I like it, though it would be more beneficial to use the instances of the classes, rather than the classes themselves, as you mentioned.

**Comment by mwbrulhardt** [comment]
Tomorrow morning I can change it to give the instances instead of the classes and push it, it would be a fast fix. Does that work?

**Comment by notadamking** [comment]
Yeah, that would be great.

**Comment by mwbrulhardt** [comment]
Made the necessary changes, only thing is the tests are failing. However, that has to do with the "AttributeError: module 'tensorflow' has no attribute 'function'" error. Look it over when you get the chance. Thanks!

**Comment by notadamking** [comment]
@mwbrulhardt Thanks for this! Will get this implemented today.

**Pull request merged**
