### PR TITLE
fixed tutorial bug - updated main tutorial

### PR DESCRIPTION
**Pull request by andrewczgithub**
Deleted a function input to make the tutorial run with out errors.

### CODE REVIEW

**Comment by notadamking** [comment]
@andrewczgithub I apologize, the commit just merged to master affects this PR.

**Comment by andrewczgithub** [comment]
now worries champion! great project. do you want me to delete this pull request?
BEst,
Andrew

**Comment by notadamking** [comment]
It would be even better if you could update the PR and apply the fixes to the latest version of the tutorial.

**Comment by andrewczgithub** [comment]
Ah no problem champion! will do :)

**Comment by notadamking** [comment]
Feel free to re-open this.

**Pull request closed without merging**
